import type { Metadata } from "next";
import type { ReactNode } from "react";
import LegalLayout from "@/components/LegalLayout";
import { legalConfig } from "@/lib/legalConfig";

export const metadata: Metadata = {
  title: "Privacy Policy | OMLU",
  description: "Learn how Nadha Labs collects, uses, protects, and manages information when restaurants, staff, and guests use OMLU.",
};

const TOC = [
  "Who Operates OMLU", "Scope of This Policy", "Our Role and the Restaurant's Role", "Information We Process", "Information You Provide", "Information Collected Automatically", "Dining and QR Ordering Information", "How We Use Information", "Legal Grounds for Processing", "Service and Security Communications", "Service Providers and Data Sharing", "International Processing", "Data Retention", "Your Privacy Rights", "Account Closure and Deletion", "Legal Disclosures", "Security", "Personal Data Breaches", "Children's Privacy", "Cookies and Local Storage", "Grievance and Privacy Contact", "Changes to This Policy",
].map((label, index) => ({ id: `section-${index + 1}`, label: `${index + 1}. ${label}` }));

const sectionClass = "scroll-mt-28 border-b border-[var(--omlu-border)] pb-10 last:border-0";
const headingClass = "text-2xl font-black tracking-[-0.025em] sm:text-[1.7rem]";
const bodyClass = "mt-4 space-y-4 text-[15px] leading-[1.75] text-[var(--omlu-text-secondary)] sm:text-base";

function PrivacySummary() {
  const items = [
    ["We don't sell personal data", "OMLU does not sell or rent personal information."],
    ["Restaurant-controlled dining data", "Restaurants control dining and order information processed through their OMLU workspace."],
    ["Limited service providers", "Information is shared only with providers required to operate OMLU."],
    ["Security by design", "Access controls and reasonable safeguards help protect information."],
  ];
  return <section aria-labelledby="privacy-at-a-glance" className="rounded-2xl border border-[var(--omlu-border)] bg-[var(--omlu-primary-surface)] p-5 sm:p-6"><h2 id="privacy-at-a-glance" className="sr-only">Privacy at a glance</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map(([title, text]) => <div key={title}><h3 className="text-sm font-black">{title}</h3><p className="mt-1.5 text-xs leading-5 text-[var(--omlu-text-secondary)]">{text}</p></div>)}</div><p className="mt-5 border-t border-[var(--omlu-border)] pt-4 text-xs text-[var(--omlu-text-muted)]">This summary is provided for convenience. The complete policy below is authoritative.</p></section>;
}

function Section({ number, title, children }: { number: number; title: string; children: ReactNode }) {
  return <section id={`section-${number}`} className={sectionClass}><p className="mb-2 text-xs font-black uppercase tracking-[0.16em] text-orange-600">Section {number}</p><h2 className={headingClass}>{title}</h2><div className={bodyClass}>{children}</div></section>;
}

export default function PrivacyPage() {
  return <LegalLayout title="Privacy Policy" subtitle="How Nadha Labs collects, uses, protects, and manages information when restaurants, staff, and guests use OMLU." activePath="/privacy" effectiveDate="7 August 2026" lastUpdatedDate="16 August 2026" toc={TOC} summary={<PrivacySummary />}>
    <div className="space-y-10">
      <Section number={1} title="Who Operates OMLU"><p>This Privacy Policy applies to the OMLU restaurant operations platform, operated by {legalConfig.legalEntityName} (&quot;Nadha Labs&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) in India.</p></Section>

      <Section number={2} title="Scope of This Policy"><p>This Policy explains how information is handled through OMLU&apos;s restaurant workspace, staff applications, QR ordering experiences, websites, and related services. It applies to restaurant customers, their authorised users, staff, and guests who interact with OMLU.</p><p>It should be read together with the other documents in the OMLU Legal Center and any privacy notice provided by the restaurant you are visiting or working with.</p></Section>

      <Section number={3} title="Our Role and the Restaurant's Role"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-[var(--omlu-border)] bg-[var(--omlu-muted-surface)] p-5"><h3 className="text-base font-black text-[var(--omlu-text-primary)]">Restaurant-controlled processing</h3><p className="mt-2 text-sm leading-6">For guest QR ordering, dining sessions, item instructions, service interactions, and restaurant bills, the relevant restaurant generally determines why information is processed. OMLU processes that information to provide the restaurant software.</p></div><div className="rounded-xl border border-[var(--omlu-border)] bg-[var(--omlu-muted-surface)] p-5"><h3 className="text-base font-black text-[var(--omlu-text-primary)]">Nadha Labs-controlled processing</h3><p className="mt-2 text-sm leading-6">Nadha Labs determines processing related to restaurant registration, authorised-user accounts, platform administration, authentication, security, fraud and abuse prevention, audit records, service communications, and account management.</p></div></div><p>These roles depend on the context. Restaurants are responsible for providing appropriate notices to their guests and staff where required.</p></Section>

      <Section number={4} title="Information We Process"><div className="space-y-5"><div><h3>Restaurant and Account Information</h3><p>Restaurant name, contact information, account details, tax settings, and workspace configuration.</p></div><div><h3>Staff Information</h3><p>Names, usernames or contact information where configured, assigned roles, and authentication information.</p></div><div><h3>Dining and Order Information</h3><p>Dining sessions, ordered items, guest instructions, timestamps, and table-related activity.</p></div><div><h3>Billing and Transaction Information</h3><p>Bills, tax information, discounts, totals, receipt information, and the payment method recorded by the restaurant. OMLU records the payment method used by the restaurant but does not itself store customers&apos; full card credentials.</p></div><div><h3>Technical Information</h3><p>IP addresses, browser or device information, logs, timestamps, security events, and related diagnostic data.</p></div><div><h3>Uploaded Content</h3><p>Menu images and other content intentionally uploaded by authorised restaurant users.</p></div></div></Section>

      <Section number={5} title="Information You Provide"><p>We receive information when a restaurant registers an account, creates authorised-user access, configures menus, prices or taxes, uploads content, contacts support, or uses OMLU&apos;s operational features. Guests may provide item choices, instructions, and other dining-session information through a restaurant&apos;s QR ordering experience.</p><div className="rounded-xl border-l-4 border-orange-500 bg-[var(--omlu-muted-surface)] p-5"><h3>AI-assisted menu extraction</h3><p className="mt-2">When a restaurant user chooses AI-assisted menu extraction, the uploaded menu image may be securely transmitted to Google Gemini to extract structured menu information. This processing is used only to provide the requested menu-extraction feature.</p></div></Section>

      <Section number={6} title="Information Collected Automatically"><p>When OMLU is used, we may automatically receive technical information such as IP address, browser and device details, request and connection timestamps, operational logs, and security events. We use this information to deliver the service, diagnose problems, maintain reliability, and protect OMLU from unauthorised or abusive activity.</p></Section>

      <Section number={7} title="Dining and QR Ordering Information"><p>Guests can browse a restaurant&apos;s QR menu without creating an OMLU account. Temporary browser and session information helps connect a guest to the correct restaurant and dining session. Ordered items, instructions, service interactions, and related timestamps are processed so the restaurant can fulfil orders, coordinate service, and prepare bills.</p><p>The relevant restaurant controls this dining information. Questions about a specific dining record should normally be directed to that restaurant.</p></Section>

      <Section number={8} title="How We Use Information"><ul><li>Provide, operate, maintain, and improve OMLU.</li><li>Authenticate authorised users and maintain separation between restaurant workspaces.</li><li>Route orders, coordinate restaurant service, calculate bills and taxes, and produce receipts.</li><li>Provide requested AI-assisted menu extraction.</li><li>Deliver operational updates and important account communications.</li><li>Monitor reliability, investigate problems, and prevent fraud, abuse, or unauthorised access.</li><li>Meet applicable legal, tax, accounting, and regulatory obligations.</li></ul></Section>

      <Section number={9} title="Legal Grounds for Processing"><p>Where required, Nadha Labs processes personal data based on consent. We may also process personal data where processing is permitted under applicable law, including circumstances in which consent is not required.</p><p>Processing may be necessary to provide requested OMLU services, maintain platform security, prevent fraud or abuse, protect legal rights, and comply with applicable legal obligations.</p></Section>

      <Section number={10} title="Service and Security Communications"><p>We may send registered contacts communications needed to operate OMLU, such as authentication messages, password resets, security notices, operational alerts, support replies, and account or subscription updates. These are service communications, not third-party advertising.</p></Section>

      <Section number={11} title="Service Providers and Data Sharing"><p><strong className="text-[var(--omlu-text-primary)]">Nadha Labs does not sell or rent personal information.</strong> We share information only as needed with service providers that help us operate and secure OMLU, subject to appropriate obligations.</p><dl className="grid gap-4 sm:grid-cols-2"><div><dt>Hosting and delivery</dt><dd>Vercel</dd></div><div><dt>Application infrastructure</dt><dd>Render and associated cloud infrastructure</dd></div><div><dt>Databases and caching</dt><dd>Managed PostgreSQL and Redis-compatible infrastructure providers</dd></div><div><dt>AI-assisted menu extraction</dt><dd>Google Gemini API, when a restaurant user chooses that feature</dd></div></dl><p>We may update our providers as OMLU evolves while continuing to limit sharing to what is reasonably necessary for the service.</p></Section>

      <Section number={12} title="International Processing"><p>Some infrastructure providers may process or store information outside India. Where international processing occurs, Nadha Labs handles those transfers in accordance with applicable Indian law and any restrictions notified by the Central Government.</p></Section>

      <Section number={13} title="Data Retention"><p>We retain information only for as long as reasonably necessary for the purposes described in this Policy, to operate and secure OMLU, and to comply with applicable legal, tax, accounting, and regulatory obligations.</p><p>Certain billing and transaction records may need to be retained for periods required by applicable tax and accounting laws. Where the restaurant is legally responsible for retaining such records, OMLU may retain them on the restaurant&apos;s behalf for the applicable period.</p><p>Security records, information associated with closed accounts, and backup copies may remain for a limited period where reasonably necessary for security, recovery, dispute handling, or legal compliance. Information is deleted or anonymised when it is no longer reasonably required.</p></Section>

      <Section number={14} title="Your Privacy Rights"><p>Depending on the context and applicable law, individuals may request:</p><ul><li>information about personal data processed by Nadha Labs;</li><li>correction of inaccurate information or completion of incomplete information;</li><li>erasure where legally applicable;</li><li>grievance redressal;</li><li>withdrawal of consent where processing relies on consent; and</li><li>nomination where available under applicable Indian privacy law.</li></ul><p>For guest dining or order data controlled by a restaurant, OMLU may direct the request to the relevant restaurant or assist that restaurant in handling it. Requests concerning Nadha Labs account or security data may be sent directly to our privacy contact.</p><p>Rights are subject to applicable law. We may verify a request and may retain information where a legal obligation or permitted security or legal purpose requires it.</p></Section>

      <Section number={15} title="Account Closure and Deletion"><p>Restaurant account owners may request closure through the OMLU privacy or support contact. After verification, access may be disabled and personal account information may be deleted or anonymised. Certain information may continue to be retained where required by law or reasonably necessary for security, fraud prevention, dispute resolution, or other legitimate legal purposes.</p></Section>

      <Section number={16} title="Legal Disclosures"><p>We may preserve or disclose information where reasonably necessary to comply with applicable law, a valid court or government request, or legal process; enforce our agreements; investigate misuse; or protect the rights, safety, and security of Nadha Labs, restaurants, users, or the public.</p></Section>

      <Section number={17} title="Security"><p>Nadha Labs uses reasonable technical and organisational safeguards designed to protect information processed through OMLU. These measures may include encryption in transit, secure credential storage, role-based access controls, tenant isolation, audit logging, rate limiting, security monitoring, and controlled infrastructure access.</p><p>No internet-based service can guarantee absolute security. Restaurants and authorised users should protect their credentials, use appropriate access permissions, and notify us promptly of suspected unauthorised access.</p></Section>

      <Section number={18} title="Personal Data Breaches"><p>If a personal data breach occurs, Nadha Labs will take appropriate steps to investigate, contain, and remediate the incident and will provide notifications to affected persons, relevant restaurant customers, and competent authorities where required by applicable law.</p></Section>

      <Section number={19} title="Children's Privacy"><p>OMLU is a restaurant operations platform and is not directed to children as an online service. Nadha Labs does not knowingly create OMLU accounts for children or intentionally collect children&apos;s personal data for independent marketing or profiling purposes.</p><p>Dining information submitted in a restaurant context remains governed by the restaurant relationship and applicable law.</p></Section>

      <Section number={20} title="Cookies and Local Storage"><p>OMLU uses necessary browser technologies, including cookies and local or session storage, for authentication, session continuity, QR ordering sessions, user preferences, draft recovery, and security. OMLU does not currently use third-party behavioural advertising cookies.</p></Section>

      <Section number={21} title="Grievance and Privacy Contact"><p>For privacy questions, rights requests, or grievances, contact:</p><address className="not-italic rounded-2xl border border-[var(--omlu-border)] bg-[var(--omlu-primary-surface)] p-6"><h3 className="text-lg">Privacy &amp; Grievance Contact</h3><p className="mt-3 font-bold text-[var(--omlu-text-primary)]">{legalConfig.legalEntityName}</p><p>Privacy / Grievance Officer</p><p>Email: <a href={`mailto:${legalConfig.privacyEmail}`}>{legalConfig.privacyEmail}</a></p><p>Location: {legalConfig.registeredAddress}</p></address></Section>

      <Section number={22} title="Changes to This Policy"><p>We may update this Privacy Policy as OMLU evolves or legal requirements change. The current version will always display its latest revision date. Where required, we will provide additional notice of material changes.</p></Section>
    </div>
  </LegalLayout>;
}
