"use client";

import { useState } from "react";
import { initialScreens, menuItems } from "@/lib/cinema/mockService";
import styles from "@/app/cinema-admin/cinema.module.css";

const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;

export default function CinemaCustomerClient({screenCode,seatCode}:{screenCode:string;seatCode:string}){
  const screen=initialScreens.find(x=>x.code.toLowerCase()===screenCode.toLowerCase())??initialScreens[1];
  const seat=screen.seats.find(x=>x.code.toLowerCase()===seatCode.toLowerCase());
  const[category,setCategory]=useState("All"),[query,setQuery]=useState(""),[cart,setCart]=useState<Record<string,number>>({}),[view,setView]=useState<"menu"|"cart"|"tracking">("menu");
  const visible=menuItems.filter(x=>x.available&&(category==="All"||x.category===category)&&`${x.name} ${x.description}`.toLowerCase().includes(query.toLowerCase()));
  const count=Object.values(cart).reduce((a,b)=>a+b,0), total=menuItems.reduce((sum,x)=>sum+(cart[x.id]??0)*x.price,0);
  const change=(id:string,delta:number)=>setCart(old=>({...old,[id]:Math.max(0,(old[id]??0)+delta)}));
  if(!seat)return <main className={styles.customer}><div className={styles.customerMain} style={{padding:30}}><h1>Seat not found</h1><p>Check the screen and seat code printed below the QR.</p></div></main>;
  if(view==="tracking")return <main className={styles.cartPanel}><div className={`${styles.cartInner} ${styles.tracking}`}><div className={styles.trackingCheck}>✓</div><p className={styles.eyebrow}>ORDER #C1049</p><h1>Your order is confirmed</h1><p>We’ll bring it quietly to {screen.name} · Seat {seat.code}.</p><div className={styles.deliveryBox} style={{textAlign:"left"}}><small>DELIVERY LOCATION</small><strong>{screen.name} · {seat.code}</strong></div><div className={styles.steps}>{["Order received","Preparing","Ready","On the way","Delivered"].map((x,i)=><div className={styles.step} data-done={i===0} key={x}>{x}</div>)}</div><button className={styles.buttonSecondary} onClick={()=>setView("menu")}>Back to menu</button></div></main>;
  if(view==="cart")return <main className={styles.cartPanel}><div className={styles.cartInner}><div className={styles.cartTop}><h1>Your order</h1><button className={styles.iconButton} aria-label="Close cart" onClick={()=>setView("menu")}>×</button></div><div className={styles.deliveryBox}><small>DELIVERY TO</small><strong>{screen.name} · Seat {seat.code}</strong></div>{menuItems.filter(x=>cart[x.id]).map(x=><div className={styles.cartItem} key={x.id}><div><strong>{x.name}</strong><div className={styles.orderMeta}>{money(x.price)} each</div></div><div className={styles.qty}><button onClick={()=>change(x.id,-1)}>−</button><span>{cart[x.id]}</span><button onClick={()=>change(x.id,1)}>+</button></div></div>)}{!count&&<div className={styles.emptyInspector}>Your cart is empty.</div>}</div><div className={styles.checkout}><div><small>Total</small><strong>{money(total)}</strong></div><button disabled={!count} className={styles.button} onClick={()=>setView("tracking")}>Place order · {money(total)}</button></div></main>;
  return <main className={styles.customer}><div className={styles.customerMain}><header className={styles.customerHero}><div className={styles.customerBrand}><strong>OMLU CINEMA</strong><div className={styles.seatBadge}>{screen.name} · {seat.code}</div></div><h1>Snacks and drinks, delivered to your seat.</h1><input aria-label="Search concessions" className={styles.customerSearch} placeholder="Search popcorn, drinks, combos…" value={query} onChange={e=>setQuery(e.target.value)}/></header><div className={styles.categories}>{["All","Popcorn","Combos","Cold Drinks","Snacks","Nachos","Water"].map(x=><button className={styles.category} data-active={category===x} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><section className={styles.customerProducts}>{visible.map(item=><article className={styles.product} key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p><strong>{money(item.price)}</strong></div><div className={styles.productVisual}>{item.name.slice(0,2).toUpperCase()}<button className={styles.add} onClick={()=>change(item.id,1)}>{cart[item.id]?`${cart[item.id]} ADDED`:"ADD"}</button></div></article>)}</section></div>{count>0&&<button className={styles.cartBar} onClick={()=>setView("cart")}><span>{count} item{count>1?"s":""}</span><span>View cart · {money(total)}</span></button>}</main>;
}
