"""create_staff_users_table

Revision ID: 57d7e2165328
Revises: ce059a6de3b2
Create Date: 2026-07-12 00:56:37.369567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d7e2165328'
down_revision: Union[str, Sequence[str], None] = 'ce059a6de3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'manager', 'kitchen', 'waiter')", name='chk_staff_user_role'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'email', name='uq_staff_user_restaurant_email')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=False)
    op.create_index(op.f('ix_staff_users_is_active'), 'staff_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_staff_users_restaurant_id'), 'staff_users', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_staff_users_role'), 'staff_users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_users_role'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_restaurant_id'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_is_active'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    # ### end Alembic commands ###
